export const db = [
{
    id: 1,
    order: '5434',
    customer: 'Gabrielle Feyer',
    email: 'gfeyer0@nyu.edu',
    avatar: '/images/avatars/8.png',
    payment: 1,
    status: 'Delivered',
    spent: 73.98,
    method: 'paypalLogo',
    date: '5/16/2022',
    time: '2:11 AM',
    industry: 'Automotive',
    url: 'https://example.com/report1',
    fileName: 'Report_123.pdf',
    totalRowCount: 150,
    leadAcceptCount: 100,
    leadRejectCount: 50,
    created: '2024-09-25',
    createdBy: 'Alice Smith',
    methodNumber: 6522

  },



  {
    id: 2,
    order: '6745',
    customer: 'Jackson Deignan',
    email: 'jdeignan1@dell.com',
    avatar: '/images/avatars/8.png',
    payment: 3,
    status: 'Delivered',
    spent: 100.39,
    method: 'paypalLogo',
    date: '5/3/2023',
    time: '7:26 PM',
    industry: 'Automotive',
    url: 'https://example.com/report2',
    fileName: 'Report_124.pdf',
    totalRowCount: 200,
    leadAcceptCount: 150,
    leadRejectCount: 50,
    created: '2024-09-26',
    createdBy: 'Bob Johnson', 
    methodNumber: 7538
  },
  {
    id: 3,
    order: '6087',
    customer: 'Tanya Crum',
    email: 'tcrum2@yandex.ru',
    avatar: '/images/avatars/7.png',
    payment: 4,
    status: 'Ready to Pickup',
    spent: 809.26,
    method: 'mastercard',
    date: '12/15/2022',
    time: '6:51 PM',
    industry: 'Automotive',
    url: 'https://example.com/report3',
    fileName: 'Report_125.pdf',
    totalRowCount: 300,
    leadAcceptCount: 250,
    leadRejectCount: 50,
    created: '2024-09-27',
    createdBy: 'Charlie Brown',
    methodNumber: 5170
  },
  {
    id: 4,
    order: '7825',
    customer: 'Dallis Dillestone',
    email: 'ddillestone3@archive.org',
    avatar: '/images/avatars/4.png',
    payment: 3,
    status: 'Ready to Pickup',
    spent: 617.64,
    method: 'paypalLogo',
    date: '8/5/2022',
    time: '9:18 PM',
    industry: 'Automotive',
    url: 'https://example.com/report1',
    fileName: 'Report_123.pdf',
    totalRowCount: 150,
    leadAcceptCount: 100,
    leadRejectCount: 50,
    created: '2024-09-25',
    createdBy: 'Alice Smith',
    methodNumber: 1748
  },
  {
    id: 5,
    order: '5604',
    customer: 'Conan Kennham',
    email: 'ckennham4@cnn.com',
    avatar: '/images/avatars/1.png',
    payment: 3,
    status: 'Delivered',
    spent: 384.41,
    method: 'mastercard',
    date: '6/18/2022',
    time: '3:34 AM',
    industry: 'Automotive',
    url: 'https://example.com/report2',
    fileName: 'Report_124.pdf',
    totalRowCount: 200,
    leadAcceptCount: 150,
    leadRejectCount: 50,
    created: '2024-09-26',
    createdBy: 'Bob Johnson',
    methodNumber: 6425
  },
  {
    id: 6,
    order: '5390',
    customer: 'Daven Brocket',
    email: 'dbrocket5@epa.gov',
    avatar: '/images/avatars/5.png',
    payment: 3,
    status: 'Out for Delivery',
    spent: 162.85,
    method: 'paypalLogo',
    date: '10/14/2022',
    time: '6:12 PM',
    industry: 'Automotive',
    url: 'https://example.com/report1',
    fileName: 'Report_123.pdf',
    totalRowCount: 150,
    leadAcceptCount: 100,
    leadRejectCount: 50,
    created: '2024-09-25',
    createdBy: 'Alice Smith',
    methodNumber: 1694
  },
  {
    id: 7,
    order: '7279',
    customer: 'Rex Farbrace',
    email: 'rfarbrace6@sourceforge.net',
    avatar: '/images/avatars/2.png',
    payment: 2,
    status: 'Out for Delivery',
    spent: 591.47,
    method: 'mastercard',
    date: '8/8/2022',
    time: '6:09 PM',
    industry: 'Automotive',
    url: 'https://example.com/report1',
    fileName: 'Report_123.pdf',
    totalRowCount: 150,
    leadAcceptCount: 100,
    leadRejectCount: 50,
    created: '2024-09-25',
    createdBy: 'Alice Smith',
    methodNumber: 1883
  },
  {
    id: 8,
    order: '7003',
    customer: 'Tann Biaggetti',
    email: 'tbiaggetti7@eepurl.com',
    avatar: '/images/avatars/8.png',
    payment: 4,
    status: 'Delivered',
    spent: 664.51,
    method: 'mastercard',
    date: '6/10/2022',
    time: '12:59 PM',
    industry: 'Automotive',
    url: 'https://example.com/report2',
    fileName: 'Report_124.pdf',
    totalRowCount: 200,
    leadAcceptCount: 150,
    leadRejectCount: 50,
    created: '2024-09-26',
    createdBy: 'Bob Johnson',
    methodNumber: 5047
  },
  {
    id: 9,
    order: '8632',
    customer: 'Abagael Drogan',
    email: 'adrogan8@storify.com',
    avatar: '/images/avatars/3.png',
    payment: 4,
    status: 'Dispatched',
    spent: 717.72,
    method: 'paypalLogo',
    date: '10/25/2022',
    time: '10:48 AM',
    industry: 'Automotive',
    url: 'https://example.com/report3',
    fileName: 'Report_125.pdf',
    totalRowCount: 300,
    leadAcceptCount: 250,
    leadRejectCount: 50,
    created: '2024-09-27',
    createdBy: 'Charlie Brown',
    methodNumber: 1945
  },
  {
    id: 10,
    order: '8501',
    customer: 'Esme Sangwin',
    email: 'esangwin9@taobao.com',
    avatar: '',
    payment: 3,
    status: 'Ready to Pickup',
    spent: 477.42,
    method: 'mastercard',
    date: '11/2/2022',
    time: '2:19 PM',
    industry: 'Automotive',
    url: 'https://example.com/report1',
    fileName: 'Report_123.pdf',
    totalRowCount: 150,
    leadAcceptCount: 100,
    leadRejectCount: 50,
    created: '2024-09-25',
    createdBy: 'Alice Smith',
    methodNumber: 3526
  }]