export const db = [
  {
    id: 1,
    customer: 'Ben Karlos',
    firstName: "Ben",
    lastName: "karlos",
    account: "Omnitrex",
    customerId: '879861',
    email: 'sbaser0@boston.com',
    country: 'Australia',
    countryFlag: '/images/cards/australia.png',
    countryCode: 'lk',
    order: 157,
    totalSpent: 2074.22,
    avatar: '/images/avatars/1.png',
    leadOwner: 'Garry Adams',
    sdr: 'Umadi Sarvani',
    industry: 'Manufacturing',
    zipCode: '10001',
    status: 'Active',
    city: 'New York',
    state: 'NY',
    createdBy: 'Admin',
    updatedBy: 'Sales Manager',
    createdDate: '2023-01-15T12:00:00Z',
    updatedDate: '2023-09-30T15:30:00Z'

  },
  {
    id: 2,
    customer: 'Laurie Dax',
    customerId: '178408',
    email: 'ldax1@lycos.com',
    country: 'Australia',
    countryFlag: '/images/cards/australia.png',
    countryCode: 'ru',
    order: 663,
    totalSpent: 2404.19,
    avatar: '/images/avatars/2.png',
    leadOwner: 'Lorena Acosta',
    sdr: 'Umadi Sarvani',
    industry: 'Technology',
    zipCode: 'M5H 2N2',
    status: 'Pending',
    city: 'Toronto',
    state: 'Ontario',
    createdBy: 'Sales Rep',
    updatedBy: 'Sales Manager',
    createdDate: '2022-11-25T09:45:00Z',
    updatedDate: '2023-09-25T10:20:00Z'
  },
  {
    id: 3,
    customer: 'Maxine Kenrick',
    customerId: '221092',
    email: 'mkenrick2@eepurl.com',
    country: 'Australia',
    countryFlag: '/images/cards/australia.png',
    countryCode: 'gt',
    order: 64,
    totalSpent: 8821.4,
    avatar: '/images/avatars/3.png',
    leadOwner: 'Ryan Costello',
    sdr: 'Umadi Sarvani',
    industry: 'Software',
    zipCode: 'EC1A 1BB',
    status: 'Closed',
    city: 'London',
    state: 'England',
    createdBy: 'Admin',
    updatedBy: 'Operations Lead',
    createdDate: '2023-02-10T11:00:00Z',
    updatedDate: '2023-10-01T12:45:00Z'
  },
  {
    id: 4,
    customer: 'Harman Burkill',
    customerId: '645579',
    email: 'hburkill3@drupal.org',
    country: 'United States',
    countryFlag: '/images/cards/us.png',
    countryCode: 'pt',
    order: 640,
    totalSpent: 5294.35,
    avatar: '/images/avatars/4.png',
    leadOwner: 'Lorena Acosta',
    sdr: 'Umadi Sarvani',
    industry: 'Technology',
    zipCode: 'M5H 2N2',
    status: 'Pending',
    city: 'Toronto',
    state: 'Ontario',
    createdBy: 'Sales Rep',
    updatedBy: 'Sales Manager',
    createdDate: '2022-11-25T09:45:00Z',
    updatedDate: '2023-09-25T10:20:00Z'
  },
  {
    id: 5,
    customer: 'Aubrey Borrow',
    customerId: '288765',
    email: 'aborrow4@jiathis.com',
    country: 'France',
    countryFlag: '/images/cards/france.png',
    countryCode: 'fr',
    order: 184,
    totalSpent: 1003.3,
    avatar: '/images/avatars/5.png',
    leadOwner: 'Garry Adams',
    sdr: 'Umadi Sarvani',
    industry: 'Manufacturing',
    zipCode: '10001',
    status: 'Active',
    city: 'New York',
    state: 'NY',
    createdBy: 'Admin',
    updatedBy: 'Sales Manager',
    createdDate: '2023-01-15T12:00:00Z',
    updatedDate: '2023-09-30T15:30:00Z'
  },
  {
    id: 6,
    customer: 'Nester Fridd',
    customerId: '321942',
    email: 'nfridd5@cdbaby.com',
    country: 'China',
    countryFlag: '/images/cards/china.png',
    countryCode: 'cn',
    order: 965,
    totalSpent: 3876.92,
    avatar: '/images/avatars/6.png',
    leadOwner: 'Ryan Costello',
    sdr: 'Umadi Sarvani',
    industry: 'Software',
    zipCode: 'EC1A 1BB',
    status: 'Closed',
    city: 'London',
    state: 'England',
    createdBy: 'Admin',
    updatedBy: 'Operations Lead',
    createdDate: '2023-02-10T11:00:00Z',
    updatedDate: '2023-10-01T12:45:00Z'
  },
  {
    id: 7,
    customer: 'Lizzie Nicholes',
    customerId: '516109',
    email: 'lnicholes6@rediff.com',
    country: 'Brazil',
    countryFlag: '/images/cards/brazil.png',
    countryCode: 'br',
    order: 514,
    totalSpent: 7936.85,
    avatar: '/images/avatars/7.png',
    leadOwner: 'Ryan Costello',
    sdr: 'Umadi Sarvani',
    industry: 'Technology',
    zipCode: 'M5H 2N2',
    status: 'Pending',
    city: 'Toronto',
    state: 'Ontario',
    createdBy: 'Sales Rep',
    updatedBy: 'Sales Manager',
    createdDate: '2022-11-25T09:45:00Z',
    updatedDate: '2023-09-25T10:20:00Z'
  },
  {
    id: 8,
    customer: 'Amabel Scullion',
    customerId: '403666',
    email: 'ascullion7@wiley.com',
    country: 'Australia',
    countryFlag: '/images/cards/australia.png',
    countryCode: 'gt',
    order: 584,
    totalSpent: 4150.97,
    avatar: '/images/avatars/8.png',

    leadOwner: 'Lorena Acosta',
    sdr: 'Umadi Sarvani',
    industry: 'Manufacturing',
    zipCode: '10001',
    status: 'Active',
    city: 'New York',
    state: 'NY',
    createdBy: 'Admin',
    updatedBy: 'Sales Manager',
    createdDate: '2023-01-15T12:00:00Z',
    updatedDate: '2023-09-30T15:30:00Z'
  },
  {
    id: 9,
    customer: 'Zeke Arton',
    customerId: '895280',
    email: 'zarton8@weibo.com',
    country: 'Australia',
    countryFlag: '/images/cards/australia.png',
    countryCode: 'ua',
    order: 539,
    totalSpent: 3430.05,
    avatar: '/images/avatars/1.png',
    leadOwner: 'Garry Adams',
    sdr: 'Umadi Sarvani',
    industry: 'Manufacturing',
    zipCode: '10001',
    status: 'Active',
    city: 'New York',
    state: 'NY',
    createdBy: 'Admin',
    updatedBy: 'Sales Manager',
    createdDate: '2023-01-15T12:00:00Z',
    updatedDate: '2023-09-30T15:30:00Z'
  },
  {
    id: 10,
    customer: 'Rosy Medlicott',
    customerId: '199195',
    email: 'rmedlicott9@amazon.com',
    country: 'Australia',
    countryFlag: '/images/cards/australia.png',
    countryCode: 'ru',
    order: 4,
    totalSpent: 8646.75,
    avatar: '/images/avatars/2.png',
    leadOwner: 'Ryan Costello',
    sdr: 'Umadi Sarvani',
    industry: 'Software',
    zipCode: 'EC1A 1BB',
    status: 'Closed',
    city: 'London',
    state: 'England',
    createdBy: 'Admin',
    updatedBy: 'Operations Lead',
    createdDate: '2023-02-10T11:00:00Z',
    updatedDate: '2023-10-01T12:45:00Z'
  },
  {
    id: 11,
    customer: 'Elene Esp',
    customerId: '317063',
    email: 'eespa@soundcloud.com',
    country: 'China',
    countryFlag: '/images/cards/china.png',
    countryCode: 'cn',
    order: 602,
    totalSpent: 5807.99,
    avatar: '/images/avatars/3.png'
  },
  {
    id: 12,
    customer: 'Cal Lavington',
    customerId: '999318',
    email: 'clavingtonb@nps.gov',
    country: 'China',
    countryFlag: '/images/cards/china.png',
    countryCode: 'bo',
    order: 779,
    totalSpent: 6677.41,
    avatar: '/images/avatars/4.png'
  },
  {
    id: 13,
    customer: 'Merrick Antcliffe',
    customerId: '804513',
    email: 'mantcliffec@php.net',
    country: 'China',
    countryFlag: '/images/cards/china.png',
    countryCode: 'cn',
    order: 267,
    totalSpent: 3340.41,
    avatar: '/images/avatars/5.png'
  },
  {
    id: 14,
    customer: 'Price Tremathack',
    customerId: '155681',
    email: 'ptremathackd@amazon.com',
    country: 'Australia',
    countryFlag: '/images/cards/australia.png',
    countryCode: 'ru',
    order: 611,
    totalSpent: 5768.17,
    avatar: '/images/avatars/6.png'
  },
  {
    id: 15,
    customer: 'Leesa Habershaw',
    customerId: '490182',
    email: 'lhabershawe@washingtonpost.com',
    country: 'China',
    countryFlag: '/images/cards/china.png',
    countryCode: 'jp',
    order: 90,
    totalSpent: 4488.03,
    avatar: '/images/avatars/7.png'
  },
  {
    id: 16,
    customer: 'Jeana Quincey',
    customerId: '760428',
    email: 'jquinceyf@yolasite.com',
    country: 'Australia',
    countryFlag: '/images/cards/australia.png',
    countryCode: 'ua',
    order: 597,
    totalSpent: 6936.49,
    avatar: '/images/avatars/1.png'
  },
  {
    id: 17,
    customer: 'Emmott Hise',
    customerId: '675190',
    email: 'ehiseg@usatoday.com',
    country: 'China',
    countryFlag: '/images/cards/china.png',
    countryCode: 'cn',
    order: 30,
    totalSpent: 7994.11,
    avatar: '/images/avatars/2.png'
  },
  {
    id: 18,
    customer: 'Griffith Weeke',
    customerId: '601134',
    email: 'gweekeh@dyndns.org',
    country: 'United States',
    countryFlag: '/images/cards/us.png',
    countryCode: 'id',
    order: 322,
    totalSpent: 5710.25,
    avatar: '/images/avatars/3.png'
  },
  {
    id: 19,
    customer: 'Ali Barnardo',
    customerId: '908144',
    email: 'abarnardoi@forbes.com',
    country: 'France',
    countryFlag: '/images/cards/france.png',
    countryCode: 'mx',
    order: 863,
    totalSpent: 7537.74,
    avatar: '/images/avatars/4.png'
  },
  {
    id: 20,
    customer: 'Powell Wornham',
    customerId: '528288',
    email: 'pwornhamj@ca.gov',
    country: 'France',
    countryFlag: '/images/cards/france.png',
    countryCode: 'cz',
    order: 812,
    totalSpent: 7801.46,
    avatar: '/images/avatars/5.png'
  },
]