export const db = [
    {
        id: 1,
        order: '5434',
        customer: 'pranav Feyer',
        email: 'gfeyer0@nyu.edu',
        avatar: '/images/avatars/8.png',
        payment: 1,
        status: 'Delivered',
        spent: 73.98,
        method: 'paypalLogo',
        date: '5/16/2022',
        time: '2:11 AM',
        assignedTo: 'Charlie Brown',
        selectedRelatedTo: 'Project C',
        relatedTo: 'Client Z',
        subject: 'Meeting Schedule',
        priority: 'Low',
        methodNumber: 6522

    },



    {
        id: 2,
        order: '6745',
        customer: 'Jackson Deignan',
        email: 'jdeignan1@dell.com',
        avatar: '/images/avatars/8.png',
        payment: 3,
        status: 'Delivered',
        spent: 100.39,
        method: 'paypalLogo',
        date: '5/3/2023',
        time: '7:26 PM',
        assignedTo: 'Bob Smith',
        selectedRelatedTo: 'Project B',
        relatedTo: 'Client Y',
        subject: 'Follow-Up',
        priority: 'Medium',
        methodNumber: 7538
    },
    {
        id: 3,
        order: '6087',
        customer: 'Tanya Crum',
        email: 'tcrum2@yandex.ru',
        avatar: '/images/avatars/7.png',
        payment: 4,
        status: 'Ready to Pickup',
        spent: 809.26,
        method: 'mastercard',
        date: '12/15/2022',
        time: '6:51 PM',
        assignedTo: 'Alice Johnson',
        selectedRelatedTo: 'Project A',
        relatedTo: 'Client X',
        subject: 'Initial Setup',
        priority: 'High',
        methodNumber: 5170
    },
    {
        id: 4,
        order: '7825',
        customer: 'Dallis Dillestone',
        email: 'ddillestone3@archive.org',
        avatar: '/images/avatars/4.png',
        payment: 3,
        status: 'Ready to Pickup',
        spent: 617.64,
        method: 'paypalLogo',
        date: '8/5/2022',
        time: '9:18 PM',
        assignedTo: 'David Wilson',
        selectedRelatedTo: 'Project D',
        relatedTo: 'Client A',
        subject: 'Budget Review',
        priority: 'High',
        methodNumber: 1748
    },
    {
        id: 5,
        order: '5604',
        customer: 'Conan Kennham',
        email: 'ckennham4@cnn.com',
        avatar: '/images/avatars/1.png',
        payment: 3,
        status: 'Delivered',
        spent: 384.41,
        method: 'mastercard',
        date: '6/18/2022',
        time: '3:34 AM',
        assignedTo: 'Eva Adams',
        selectedRelatedTo: 'Project E',
        relatedTo: 'Client B',
        subject: 'Contract Update',
        priority: 'Medium',
        methodNumber: 6425
    },
    {
        id: 6,
        order: '5390',
        customer: 'Daven Brocket',
        email: 'dbrocket5@epa.gov',
        avatar: '/images/avatars/5.png',
        payment: 3,
        status: 'Out for Delivery',
        spent: 162.85,
        method: 'paypalLogo',
        date: '10/14/2022',
        time: '6:12 PM',
        assignedTo: 'Frank Harris',
        selectedRelatedTo: 'Project F',
        relatedTo: 'Client C',
        subject: 'Proposal Submission',
        priority: 'High',
        methodNumber: 1694
    },
    {
        id: 7,
        order: '7279',
        customer: 'Rex Farbrace',
        email: 'rfarbrace6@sourceforge.net',
        avatar: '/images/avatars/2.png',
        payment: 2,
        status: 'Out for Delivery',
        spent: 591.47,
        method: 'mastercard',
        date: '8/8/2022',
        time: '6:09 PM',
        assignedTo: 'Grace Lee',
        selectedRelatedTo: 'Project G',
        relatedTo: 'Client D',
        subject: 'Task Assignment',
        priority: 'Low',
        methodNumber: 1883
    },
    {
        id: 8,
        order: '7003',
        customer: 'Tann Biaggetti',
        email: 'tbiaggetti7@eepurl.com',
        avatar: '/images/avatars/8.png',
        payment: 4,
        status: 'Delivered',
        spent: 664.51,
        method: 'mastercard',
        date: '6/10/2022',
        time: '12:59 PM',
        assignedTo: 'Henry Moore',
        selectedRelatedTo: 'Project H',
        relatedTo: 'Client E',
        subject: 'Performance Review',
        priority: 'Medium',
        methodNumber: 5047
    },
    {
        id: 9,
        order: '8632',
        customer: 'Abagael Drogan',
        email: 'adrogan8@storify.com',
        avatar: '/images/avatars/3.png',
        payment: 4,
        status: 'Dispatched',
        spent: 717.72,
        method: 'paypalLogo',
        date: '10/25/2022',
        time: '10:48 AM',
        assignedTo: 'Eva Adams',
        selectedRelatedTo: 'Project E',
        relatedTo: 'Client B',
        subject: 'Contract Update',
        priority: 'Medium',
        methodNumber: 1945
    },
    {
        id: 10,
        order: '8501',
        customer: 'Esme Sangwin',
        email: 'esangwin9@taobao.com',
        avatar: '',
        payment: 3,
        status: 'Ready to Pickup',
        spent: 477.42,
        method: 'mastercard',
        date: '11/2/2022',
        time: '2:19 PM',
        assignedTo: 'Grace Lee',
        selectedRelatedTo: 'Project G',
        relatedTo: 'Client D',
        subject: 'Task Assignment',
        priority: 'Low',
        methodNumber: 3526
    },
    {
        id: 11,
        order: '6498',
        customer: 'Jarib Siverns',
        email: 'jsivernsa@dailymail.co.uk',
        avatar: '',
        payment: 4,
        status: 'Out for Delivery',
        spent: 71.42,
        method: 'mastercard',
        date: '8/25/2022',
        time: '8:15 PM',
        methodNumber: 8325
    },
    {
        id: 12,
        order: '7820',
        customer: 'Christie Le Moucheux',
        email: 'cleb@wikia.com',
        avatar: '/images/avatars/8.png',
        payment: 1,
        status: 'Delivered',
        spent: 894.55,
        method: 'paypalLogo',
        date: '11/3/2022',
        time: '11:31 AM',
        methodNumber: 2034
    },
    {
        id: 13,
        order: '8229',
        customer: 'Debby Albury',
        email: 'dalburyc@homestead.com',
        avatar: '',
        payment: 2,
        status: 'Delivered',
        spent: 279.8,
        method: 'mastercard',
        date: '3/21/2023',
        time: '3:28 PM',
        methodNumber: 2751
    },
    {
        id: 14,
        order: '9076',
        customer: 'Alexia Speaks',
        email: 'aspeaksd@omniture.com',
        avatar: '',
        payment: 2,
        status: 'Dispatched',
        spent: 156.41,
        method: 'paypalLogo',
        date: '11/26/2022',
        time: '9:16 PM',
        methodNumber: 3234
    },
    {
        id: 15,
        order: '6045',
        customer: 'Orel Leamy',
        email: 'oleamye@cbc.ca',
        avatar: '',
        payment: 2,
        status: 'Delivered',
        spent: 614.39,
        method: 'mastercard',
        date: '11/20/2022',
        time: '11:58 PM',
        methodNumber: 5209
    },
    {
        id: 16,
        order: '8005',
        customer: 'Maurits Nealey',
        email: 'mnealeyf@japanpost.jp',
        avatar: '/images/avatars/7.png',
        payment: 1,
        status: 'Delivered',
        spent: 203.72,
        method: 'mastercard',
        date: '4/22/2023',
        time: '3:01 PM',
        methodNumber: 1555
    },
    {
        id: 17,
        order: '6917',
        customer: 'Emmalee Mason',
        email: 'emasong@rakuten.co.jp',
        avatar: '',
        payment: 4,
        status: 'Dispatched',
        spent: 491.83,
        method: 'mastercard',
        date: '9/1/2022',
        time: '10:31 PM',
        methodNumber: 7013
    },
    {
        id: 18,
        order: '6918',
        customer: 'Tibold Schops',
        email: 'tschopsh@reference.com',
        avatar: '/images/avatars/7.png',
        payment: 4,
        status: 'Out for Delivery',
        spent: 708.43,
        method: 'paypalLogo',
        date: '6/15/2022',
        time: '11:03 AM',
        methodNumber: 4636
    },
    {
        id: 19,
        order: '8733',
        customer: 'Godwin Greatbanks',
        email: 'ggreatbanksi@guardian.co.uk',
        avatar: '',
        payment: 2,
        status: 'Out for Delivery',
        spent: 849.78,
        method: 'paypalLogo',
        date: '8/31/2022',
        time: '10:02 AM',
        methodNumber: 6846
    },
    {
        id: 20,
        order: '6630',
        customer: 'Conn Cathery',
        email: 'ccatheryj@w3.org',
        avatar: '',
        payment: 2,
        status: 'Dispatched',
        spent: 855.31,
        method: 'paypalLogo',
        date: '1/2/2023',
        time: '4:35 PM',
        methodNumber: 4813
    },
    {
        id: 21,
        order: '8963',
        customer: 'Riccardo McKerton',
        email: 'rmckertonk@gravatar.com',
        avatar: '/images/avatars/2.png',
        payment: 2,
        status: 'Dispatched',
        spent: 458.76,
        method: 'paypalLogo',
        date: '9/17/2022',
        time: '6:00 AM',
        methodNumber: 8197
    },
    {
        id: 22,
        order: '6916',
        customer: 'Isa Cartmel',
        email: 'icartmell@scientificamerican.com',
        avatar: '/images/avatars/2.png',
        payment: 3,
        status: 'Dispatched',
        spent: 914.48,
        method: 'paypalLogo',
        date: '12/21/2022',
        time: '8:35 PM',
        methodNumber: 2844
    },
    {
        id: 23,
        order: '6647',
        customer: 'Yoko Beetles',
        email: 'ybeetlesm@discovery.com',
        avatar: '/images/avatars/7.png',
        payment: 1,
        status: 'Delivered',
        spent: 948.07,
        method: 'mastercard',
        date: '1/24/2023',
        time: '12:01 AM',
        methodNumber: 2562
    },
    {
        id: 24,
        order: '8044',
        customer: 'Nowell Cornford',
        email: 'ncornfordn@sogou.com',
        avatar: '/images/avatars/5.png',
        payment: 4,
        status: 'Ready to Pickup',
        spent: 525.6,
        method: 'paypalLogo',
        date: '8/22/2022',
        time: '6:36 PM',
        methodNumber: 2030
    },
    {
        id: 25,
        order: '9879',
        customer: 'Brandy McIlvenna',
        email: 'bmcilvennao@51.la',
        avatar: '',
        payment: 1,
        status: 'Out for Delivery',
        spent: 100.18,
        method: 'mastercard',
        date: '12/23/2022',
        time: '7:14 AM',
        methodNumber: 4686
    },
    {
        id: 26,
        order: '5551',
        customer: 'Zondra Klimkin',
        email: 'zklimkinp@ed.gov',
        avatar: '/images/avatars/1.png',
        payment: 3,
        status: 'Delivered',
        spent: 463.32,
        method: 'mastercard',
        date: '12/20/2022',
        time: '12:01 PM',
        methodNumber: 6209
    },
    {
        id: 27,
        order: '5905',
        customer: 'Elyn Aizic',
        email: 'eaizicq@live.com',
        avatar: '',
        payment: 4,
        status: 'Dispatched',
        spent: 581.81,
        method: 'mastercard',
        date: '6/1/2022',
        time: '2:31 AM',
        methodNumber: 7031
    },
    {
        id: 28,
        order: '7616',
        customer: 'Leoine Talbot',
        email: 'ltalbotr@prweb.com',
        avatar: '',
        payment: 1,
        status: 'Delivered',
        spent: 118.75,
        method: 'paypalLogo',
        date: '10/13/2022',
        time: '12:57 AM',
        methodNumber: 4387
    },
    {
        id: 29,
        order: '6624',
        customer: 'Fayre Screech',
        email: 'fscreechs@army.mil',
        avatar: '',
        payment: 3,
        status: 'Out for Delivery',
        spent: 774.91,
        method: 'mastercard',
        date: '4/17/2023',
        time: '6:43 PM',
        methodNumber: 2077
    },
    {
        id: 30,
        order: '8653',
        customer: 'Roxanne Rablen',
        email: 'rrablent@alexa.com',
        avatar: '',
        payment: 1,
        status: 'Delivered',
        spent: 212.75,
        method: 'mastercard',
        date: '3/23/2023',
        time: '10:07 PM',
        methodNumber: 2696
    },
    {
        id: 31,
        order: '8076',
        customer: 'Rebekkah Newsham',
        email: 'rnewshamu@hhs.gov',
        avatar: '/images/avatars/2.png',
        payment: 2,
        status: 'Ready to Pickup',
        spent: 778.56,
        method: 'mastercard',
        date: '7/1/2022',
        time: '10:37 PM',
        methodNumber: 8071
    },
]